server.port: 80

spring.datasource:
  url : jdbc:postgresql://localhost:5432/ecomm
  username: postgres
  password: ENC(t0ADr6e0/4nZxomqfQCWRK2oIKgUIWO3)

spring.jpa:
  show-sql: true
  generate-ddl: true
  allowed.origins: http://localhost:4200
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
    #spring.sql.init.mode=always

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: mageek@gmail.com
    password: password
    properties:
      mail.transport.protocol: smtps
      mail.smtps.auth: true
      mail.smtps.starttls.enable: true
      mail.smtps.timeout: 8000

management:
  endpoints:
    web:
      exposure:
        include: health,info,readiness,liveness
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessprobe:
      enabled: true
      initialDelay: 30s
      period: 10s
      timeout: 5s
      failureThreshold: 3
      successThreshold: 1
    livenessprobe:
      enabled: true





