server.port: 80

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: ${JASYPT_ENCRYPTOR_PASSWORD:your-secret-key}

spring.datasource:
  url: jdbc:postgresql://localhost:5432/ecomm
  username: postgres
  password: ENC(AD1lJD8SrVlb2zgdtdaX8ybVHO5yjQ95X7Wwetg5/Rs=)  # Replace the encrypted password temporarily with the actual password

spring.jpa:
  show-sql: true
  generate-ddl: true
  allowed.origins: http://localhost:4200
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update

# uncomment to fill data to DB
#  spring.sql:
#    init:
#      mode: always

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: mageek@gmail.com
    password: password
    properties:
      mail.transport.protocol: smtps
      mail.smtps.auth: true
      mail.smtps.starttls.enable: true
      mail.smtps.timeout: 8000

management:
  endpoints:
    web:
      exposure:
        include: health,info,readiness,liveness
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessprobe:
      enabled: true
      initialDelay: 30s
      period: 10s
      timeout: 5s
      failureThreshold: 3
      successThreshold: 1
    livenessprobe:
      enabled: true





